INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('ananas mrożony', 0, 0.01, 0.14, 0.63)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Ananas plastry w lekkim syropiw Nasza Spiżarnia', 0, 0, 0.16, 0.67)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('banan', 0, 0.01, 0.22, 0.97)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('brokuł mrożony', 0, 0.02, 0.05, 0.15)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('bułka tarta', 0.03, 0.13, 0.7, 3.68)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('chleb PIEKARNIA DLA CIEBIE', 0.01, 0.08, 0.49, 2.45)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('chleb pszenno-żytni wypieczone ze smakiem 900 g', 0.01, 0.07, 0.47, 2.31)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Chleb Stołowy', 0.03, 0.09, 0.46, 2.53)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('chleb żytnia biedronka (1 kromka = 32.5 g)', 0.07, 0.05, 0.31, 2.29)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('filet z kurczaka', 0.01, 0.22, 0, 0.98)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Filet z makreli w sosie pomidorowym (puszka netto 170 g)', 0.15, 0.1, 0.05, 1.96)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Fix Knorr 4 sery + brokuły', 0.28, 0.12, 0.44, 4.77)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Flora Original', 0.45, 0.01, 0.01, 3.98)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Frankfurterki wędzone Kraina Wędlin', 0.25, 0.16, 0.05, 3.26)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('jabłko', 0, 0, 0.1, 0.5)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('jajko gotowane (kl. L 1 szt = 56 g)', 0.1, 0.13, 0.01, 1.4)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('kapusta biała', 0, 0.02, 0.05, 0.33)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('kaszanka', 0.13, 0.09, 0.13, 1.95)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('kiełbasa krakowska parzona kraina wędlin', 0.04, 0.18, 0.02, 1.15)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('kiełkaski śląskie z szynki Kraina Wędlin', 0.19, 0.17, 0.02, 2.45)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('kotlety sojowe smażone', 0.2, 0.19, 0.21, 3.19)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('kotlety sojowe surowe', 0.01, 0.45, 0.24, 3.21)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('kurczak curry z mlekiem kokosowym', 0.1, 0.11, 0.11, 1.78)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('majonez Winiary (na 100 ml - jedna łyżka 15 ml)', 0.76, 0.02, 0.03, 7.04)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('makaron tagiatelle', 0.02, 0.12, 0.73, 3.64)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('mango mrożone', 0, 0.01, 0.14, 0.77)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('maślanka', 0.02, 0.03, 0.05, 0.47)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('mięso mielone wieprzowo wołowe Biedronka', 0.13, 0.19, 0, 1.88)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('mięso mielone z łopatki wieprzowej Biedronka', 0.15, 0.19, 0, 2.12)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('mleko kokosowe', 0.18, 0.01, 0.02, 1.69)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('olej rzepakowy', 0.92, 0, 0, 8.28)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('PAPIRUS z kurczakiem', 0.03, 0.21, 0.01, 1.12)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('parówki wędzone z kurcząt  BIEDRONKA (1 szt = 62.5 g)', 0.19, 0.13, 0.02, 2.33)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('płatki jęczmienne (suche)', 0.04, 0.11, 0.7, 3.7)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('płatki owsiane błyskawiczne', 0.06, 0.13, 0.6, 3.63)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('pomarańcza', 0, 0.01, 0.09, 0.47)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Rama Classic', 0.6, 0, 0, 5.32)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('ryż biały długoziarnisty (suchy)', 0.01, 0.08, 0.78, 3.53)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('ryż brązowy długoziarnisty', 0.02, 0.08, 0.75, 3.41)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('ser żółty światowid BIEDRONKA (1 plaster = 13.9 g)', 0.26, 0.24, 0, 3.3)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('serek do smarowania Delikate', 0.22, 0.08, 0.04, 2.45)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('serek wiejski Krasnystaw 200 g', 0.05, 0.11, 0.02, 0.97)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Słonecznik łuskany Mix Tentor', 0.45, 0.18, 0.22, 5.56)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Szprot w sosie pomidorowym Marinero', 0.08, 0.11, 0.05, 1.34)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('szynka konserwowa kraina wędlin (1 plasterek = 14.25 g)', 0.02, 0.19, 0.01, 0.99)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('Szynka zawędzana KRAINA WĘDLIN', 0.02, 0.18, 0.03, 1.02)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('śmietana 12% Mleczna Dolina', 0.12, 0.03, 0.04, 1.34)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('śmietana 18% Bieluch', 0.18, 0.03, 0.04, 1.86)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('tagiatelle 4 sery i brokuły', 1.73, 0.77, 2.75, 1.55)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('TopChips paprykowe', 0.35, 0.06, 0.48, 5.37)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('truskawki mrożone', 0, 0, 0.07, 0.35)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('twaróg półtłusty', 0.04, 0.14, 0.04, 1.14)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('vitanella mleko i zboża', 0.12, 0.08, 0.71, 4.37)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('warzywa na patelnie po grecku (Biedronka)', 0.01, 0.02, 0.09, 0.5)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('warzywa na patelnie po włosku (Biedronka)', 0.01, 0.02, 0.04, 0.34)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('warzywa na patelnie z ziemniakami (Biedronka)', 0.01, 0.02, 0.12, 0.66)
INSERT INTO Products (ProductName, Fat, Carbohydrates, Protein, Energy) VALUES('ziemniaki gotowane', 0, 0.02, 0.15, 0.71)
